//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::cv_detect::Entity as CvDetect;
pub use super::rfid_detect::Entity as RfidDetect;
pub use super::rfid_spool::Entity as RfidSpool;
